- name: restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: restart zabbix-agent2
  service:
    name: zabbix-agent2
    state: restarted
    enabled: yes
